package com.mslynch.awesomesource.organize.persistence.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.mslynch.awesomesource.organize.model.FileStatus
import com.mslynch.awesomesource.organize.model.LibraryType
import com.mslynch.awesomesource.organize.model.MetadataSource
import com.mslynch.awesomesource.organize.model.ReviewStatus

/**
 * One row per scanned file. `path` (library-root-relative, see LibraryPath) is the
 * primary key rather than an autogenerated id, since it's the stable identity a
 * rescan needs to match a file back to its existing row.
 */
@Entity(tableName = "tracks")
data class TrackEntity(
    @PrimaryKey val path: String,
    val uri: String,
    val fileFormat: String,
    val artist: String?,
    val albumArtist: String?,
    val album: String?,
    val title: String?,
    val trackNumber: Int?,
    val trackTotal: Int?,
    val discNumber: Int?,
    val discTotal: Int?,
    val year: Int?,
    val genre: String?,
    val durationSeconds: Double?,
    val hasCoverArt: Boolean,
    val coverArtMime: String?,
    val composer: String?,
    val libraryType: LibraryType?,
    val fileSizeBytes: Long,
    val source: MetadataSource,
    val status: FileStatus,
    val statusDetail: String,
    /** Set whenever the pipeline found a confident match (MusicBrainz auto-apply or
     * a Gemini-grounded confirmation), regardless of whether this track's own
     * fields were already complete - see [reviewStatus]. */
    val matchedReleaseId: String? = null,
    /** The matched release's proposed values, held as a draft alongside the
     * track's own (possibly incomplete) fields above - populated only when
     * [reviewStatus] would be [ReviewStatus.MATCH_FOUND]. Never written into the
     * fields above or the file itself until the user explicitly accepts it. */
    val proposedArtist: String? = null,
    val proposedAlbumArtist: String? = null,
    val proposedAlbum: String? = null,
    val proposedTitle: String? = null,
    val proposedTrackNumber: Int? = null,
    val proposedYear: Int? = null,
)

/** The four-way review classification the Library screen groups/filters by,
 * recomputed fresh from this entity's own current fields every time rather than
 * stored as its own column - see [ReviewStatus]'s doc comment for why: a manual
 * edit (or accepting a draft) can never leave a stale status behind, because there
 * is nowhere for a stale status to be stored. */
fun TrackEntity.reviewStatus(): ReviewStatus {
    val hasAllDetails = !artist.isNullOrBlank() && !album.isNullOrBlank() && !title.isNullOrBlank() && trackNumber != null
    return ReviewStatus.compute(hasAllDetails, recognized = matchedReleaseId != null)
}

/** One row per (name, role) artist credit on a track - see ArtistCredit's doc
 * comment for why a collab/remix/VIP splits into several of these per track. */
@Entity(tableName = "track_artist_credits", primaryKeys = ["trackPath", "artistName", "role"])
data class TrackArtistCreditEntity(
    val trackPath: String,
    val artistName: String,
    val role: String, // ArtistCreditRole.name
)

@Entity(tableName = "libraries")
data class LibraryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val type: LibraryType,
    val rootUri: String,
)

/**
 * Metadata for formats that can't hold embedded tags (WAV etc.), keyed by the
 * file's path - the "list document" Claude/MUSIC ORGANIZATION.md calls for, so the
 * organization pipeline never attempts a doomed in-file write for these formats and
 * instead reads/writes metadata here.
 */
@Entity(tableName = "sidecar_metadata")
data class SidecarMetadataEntity(
    @PrimaryKey val path: String,
    val artist: String?,
    val albumArtist: String?,
    val album: String?,
    val title: String?,
    val trackNumber: Int?,
    val year: Int?,
    val genre: String?,
    val composer: String?,
    val coverArtUri: String?,
)

@Entity(tableName = "scan_sessions")
data class ScanSessionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val rootFoldersJson: String,
    val startedAt: String,
    val completedAt: String?,
    val status: String,
)

/** The undo log: mirrors db.py's `tag_changes` table exactly - the primary
 * reversibility mechanism, so "don't corrupt files" holds on Android too. */
@Entity(tableName = "tag_changes")
data class TagChangeEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sessionId: Long?,
    val filePath: String,
    val fieldName: String,
    val oldValue: String?,
    val newValue: String?,
    val batchId: String,
    val appliedAt: String,
    val undone: Boolean = false,
)

@Entity(tableName = "mb_query_cache")
data class MbQueryCacheEntity(
    @PrimaryKey val queryKey: String,
    val responseJson: String,
    val cachedAt: String,
)

/** Caches a Gemini grounding-pass response per candidate set, for the same reason
 * `mb_query_cache` exists - re-querying an LLM for every rescan of an
 * already-resolved album is slow and wasteful to repeat. */
@Entity(tableName = "gemini_grounding_cache")
data class GeminiGroundingCacheEntity(
    @PrimaryKey val queryKey: String,
    val responseJson: String,
    val cachedAt: String,
)
