package com.mslynch.awesomesource.organize.persistence.entity

import android.net.Uri
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.mslynch.awesomesource.organize.model.FileStatus
import com.mslynch.awesomesource.organize.model.LibraryPath
import com.mslynch.awesomesource.organize.model.LibraryType
import com.mslynch.awesomesource.organize.model.MetadataSource
import com.mslynch.awesomesource.organize.model.ReviewStatus
import com.mslynch.awesomesource.organize.model.TrackMetadata

/**
 * One row per scanned file. `path` (library-root-relative, see LibraryPath) is the
 * primary key rather than an autogenerated id, since it's the stable identity a
 * rescan needs to match a file back to its existing row.
 */
@Entity(tableName = "tracks")
data class TrackEntity(
    @PrimaryKey val path: String,
    val uri: String,
    val fileFormat: String,
    val artist: String?,
    val albumArtist: String?,
    val album: String?,
    val title: String?,
    val trackNumber: Int?,
    val trackTotal: Int?,
    val discNumber: Int?,
    val discTotal: Int?,
    val year: Int?,
    val genre: String?,
    val durationSeconds: Double?,
    val hasCoverArt: Boolean,
    val coverArtMime: String?,
    /** A local `file://`-loadable absolute path to a cached copy of this track's
     * embedded artwork, extracted by `AudioTagReader.cacheArtwork` - for the
     * Library row thumbnail. Null for tracks with no embedded art (the row falls
     * back to a Cover Art Archive URL keyed by [matchedReleaseId] if one exists, or
     * a placeholder icon otherwise - see `ui/LibraryScreen.kt`'s `TrackRow`). */
    val coverArtPath: String? = null,
    val composer: String?,
    val libraryType: LibraryType?,
    val fileSizeBytes: Long,
    val source: MetadataSource,
    val status: FileStatus,
    val statusDetail: String,
    /** Set whenever the pipeline found a confident match (MusicBrainz auto-apply or
     * a Gemini-grounded confirmation), regardless of whether this track's own
     * fields were already complete - see [reviewStatus]. */
    val matchedReleaseId: String? = null,
    /** The matched release's proposed values, held as a draft alongside the
     * track's own (possibly incomplete) fields above - populated only when
     * [reviewStatus] would be [ReviewStatus.MATCH_FOUND]. Never written into the
     * fields above or the file itself until the user explicitly accepts it. */
    val proposedArtist: String? = null,
    val proposedAlbumArtist: String? = null,
    val proposedAlbum: String? = null,
    val proposedTitle: String? = null,
    val proposedTrackNumber: Int? = null,
    val proposedYear: Int? = null,
)

/** True once a track has been matched (by the pipeline or a Gemini-grounded
 * confirmation) or manually/bulk-edited by the user - the point past which a rescan
 * must never touch it again. The database row *is* the protected, authoritative
 * record for a curated track (never the file itself, which this app never writes
 * to) - a rescan re-reading the file's raw tags and blindly overwriting an already-
 * curated row would silently discard real work (an accepted match, a manual
 * correction, a still-pending proposed draft) for no reason, since nothing about
 * the file itself ever changes just because the app scanned it again. See
 * `OrganizeLibrary.organize()`'s tag-reading loop, which skips re-processing any
 * track this returns true for entirely - not just protecting its stored fields, but
 * not re-grouping/re-querying it either, since there is nothing left for either
 * scan to usefully do. Not a stand-in for tag-writing - it's independent of whether
 * the file itself ever gets updated, and would be exactly as necessary even if it
 * did, since a rescan is not the same event as an intentional file edit. */
fun TrackEntity.isCurated(): Boolean = matchedReleaseId != null || source == MetadataSource.MANUAL_ENTRY

/** The four-way review classification the Library screen groups/filters by,
 * recomputed fresh from this entity's own current fields every time rather than
 * stored as its own column - see [ReviewStatus]'s doc comment for why: a manual
 * edit (or accepting a draft) can never leave a stale status behind, because there
 * is nowhere for a stale status to be stored.
 *
 * `artistConfirmed` catches a real bug found via a bulk-edit on a real
 * collaboration-heavy album: a track can already have every field filled in (often
 * from a bulk edit that set one flat Artist across many tracks at once) while still
 * being matched to a confirmed release whose own per-track artist credit disagrees -
 * e.g. a track tagged "Skrillex" that the matched release's own tracklist says is
 * really "Skrillex, Missy Elliott & Mr. Oizo". Treating that as "nothing to do" would
 * silently discard a correction the pipeline already knows about (`proposedArtist`
 * is only ever populated when a track is `recognized` - see `OrganizeLibrary.processGroup`) -
 * so a real disagreement here downgrades an otherwise-"complete" track out of
 * APPROVED into MATCH_FOUND, surfacing the correction as a normal draft to accept. */
fun TrackEntity.reviewStatus(): ReviewStatus {
    val hasAllDetails = !artist.isNullOrBlank() && !album.isNullOrBlank() && !title.isNullOrBlank() && trackNumber != null
    val artistConfirmed = proposedArtist.isNullOrBlank() || proposedArtist.trim().equals(artist?.trim(), ignoreCase = true)
    return ReviewStatus.compute(hasAllDetails && artistConfirmed, recognized = matchedReleaseId != null)
}

/** The reverse of `OrganizeLibrary.persistTrack`'s `TrackMetadata -> TrackEntity`
 * mapping - used to feed an already-persisted track back through the matching
 * pipeline (grouping/MusicBrainz/Gemini) for a re-query after a manual edit, without
 * needing a fresh SAF scan. `proposed*`/`matchedReleaseId` have no `TrackMetadata`
 * equivalent and are intentionally dropped here; a re-query starts from the track's
 * own real fields only. */
fun TrackEntity.toTrackMetadata(): TrackMetadata = TrackMetadata(
    uri = Uri.parse(uri),
    path = LibraryPath(path),
    fileFormat = fileFormat,
    artist = artist,
    albumArtist = albumArtist,
    album = album,
    title = title,
    trackNumber = trackNumber,
    trackTotal = trackTotal,
    discNumber = discNumber,
    discTotal = discTotal,
    year = year,
    genre = genre,
    durationSeconds = durationSeconds,
    hasCoverArt = hasCoverArt,
    coverArtMime = coverArtMime,
    coverArtPath = coverArtPath,
    composer = composer,
    libraryType = libraryType,
    fileSizeBytes = fileSizeBytes,
    source = source,
    status = status,
    statusDetail = statusDetail,
)

/** One row per (name, role) artist credit on a track - see ArtistCredit's doc
 * comment for why a collab/remix/VIP splits into several of these per track. */
@Entity(tableName = "track_artist_credits", primaryKeys = ["trackPath", "artistName", "role"])
data class TrackArtistCreditEntity(
    val trackPath: String,
    val artistName: String,
    val role: String, // ArtistCreditRole.name
)

@Entity(tableName = "libraries")
data class LibraryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val type: LibraryType,
    val rootUri: String,
)

/**
 * Metadata for formats that can't hold embedded tags (WAV etc.), keyed by the
 * file's path - the "list document" Claude/MUSIC ORGANIZATION.md calls for, so the
 * organization pipeline never attempts a doomed in-file write for these formats and
 * instead reads/writes metadata here.
 */
@Entity(tableName = "sidecar_metadata")
data class SidecarMetadataEntity(
    @PrimaryKey val path: String,
    val artist: String?,
    val albumArtist: String?,
    val album: String?,
    val title: String?,
    val trackNumber: Int?,
    val year: Int?,
    val genre: String?,
    val composer: String?,
    val coverArtUri: String?,
)

@Entity(tableName = "scan_sessions")
data class ScanSessionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val rootFoldersJson: String,
    val startedAt: String,
    val completedAt: String?,
    val status: String,
)

/** The undo log: mirrors db.py's `tag_changes` table exactly - the primary
 * reversibility mechanism, so "don't corrupt files" holds on Android too. */
@Entity(tableName = "tag_changes")
data class TagChangeEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sessionId: Long?,
    val filePath: String,
    val fieldName: String,
    val oldValue: String?,
    val newValue: String?,
    val batchId: String,
    val appliedAt: String,
    val undone: Boolean = false,
)

@Entity(tableName = "mb_query_cache")
data class MbQueryCacheEntity(
    @PrimaryKey val queryKey: String,
    val responseJson: String,
    val cachedAt: String,
)

/** Caches a Gemini grounding-pass response per candidate set, for the same reason
 * `mb_query_cache` exists - re-querying an LLM for every rescan of an
 * already-resolved album is slow and wasteful to repeat. */
@Entity(tableName = "gemini_grounding_cache")
data class GeminiGroundingCacheEntity(
    @PrimaryKey val queryKey: String,
    val responseJson: String,
    val cachedAt: String,
)
